
server:
  port: 10001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petcelsius?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: java.text.SimpleDateFormat
  redis:
    database: 0
    host: 192.168.56.101
    port: 6379
    password: # 如果未单独配置默认为空即可
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
#    store-type: redis
    timeout: 3600s
#    邮件配置
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 749062870@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: nusuizwbxcmvbdaf
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtps
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1





