# Generated by Django 4.0.3 on 2022-04-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('alter_time', models.DateTimeField(auto_now=True)),
                ('del_mark', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('topic', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
