# Generated by Django 4.0.3 on 2022-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0006_remove_indexbanner_alter_time_remove_user_alter_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexbanner',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='del_mark',
            field=models.BooleanField(default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='del_mark',
            field=models.BooleanField(default=False, null=True, verbose_name='删除标记'),
        ),
        migrations.AlterField(
            model_name='user',
            name='topic',
            field=models.TextField(null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
