# Generated by Django 4.0.3 on 2022-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0008_rename_update_time_indexbanner_alter_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexNavigate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('del_mark', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='导航名称')),
                ('icon', models.ImageField(upload_to='', verbose_name='导航图片')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页导航栏',
                'verbose_name_plural': '首页导航栏',
                'db_table': 'index_navigate',
            },
        ),
    ]
