# Generated by Django 4.0.3 on 2022-04-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0009_indexnavigate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('del_mark', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='楼层名称')),
                ('title_img', models.ImageField(upload_to='', verbose_name='楼层标题logo')),
                ('floor_index_img', models.ImageField(upload_to='', verbose_name='楼层示图')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页楼层',
                'verbose_name_plural': '首页楼层',
                'db_table': 'index_floor',
            },
        ),
        migrations.CreateModel(
            name='IndexFloorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('del_mark', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexFloorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('del_mark', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('index', models.IntegerField(default=1, verbose_name='排序')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userBack.indexfloordetail', verbose_name='所有内容')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userBack.indexfloor', verbose_name='所属楼层')),
            ],
            options={
                'verbose_name': '首页楼层图片',
                'verbose_name_plural': '首页楼层图片',
                'db_table': 'index_floor_img',
            },
        ),
    ]
