# Generated by Django 4.0.3 on 2022-04-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0010_indexfloor_indexfloordetail_indexfloorimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexfloordetail',
            options={'verbose_name': '首页楼层详情', 'verbose_name_plural': '首页楼层详情'},
        ),
        migrations.AlterModelTable(
            name='indexfloordetail',
            table='index_floor_detail',
        ),
    ]
