# Generated by Django 4.0.3 on 2022-04-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0011_alter_indexfloordetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexfloorimage',
            name='floor_img',
            field=models.ImageField(default='null', upload_to='', verbose_name='楼层内容图'),
            preserve_default=False,
        ),
    ]
