# Generated by Django 4.0.3 on 2022-04-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0014_heartdetail_petinfo_heartinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartdetail',
            options={'verbose_name': '缅怀详情', 'verbose_name_plural': '缅怀详情'},
        ),
        migrations.AlterModelTable(
            name='heartdetail',
            table='heart_detail',
        ),
    ]
