# Generated by Django 4.0.3 on 2022-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0016_heardetailimage_petcooperateinfo_petcooperatedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCooperateDescImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('alter_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('del_mark', models.BooleanField(default=False, null=True, verbose_name='删除标记')),
                ('desc_img', models.ImageField(upload_to='', verbose_name='机构外貌')),
            ],
            options={
                'verbose_name': '合作机构详情图片',
                'verbose_name_plural': '合作机构详情图片',
                'db_table': 'cooperate_desc_img',
            },
        ),
        migrations.AddField(
            model_name='petcooperateinfo',
            name='desc',
            field=models.TextField(default='fwefqweftewfqwefwe', verbose_name='机构详情描述'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PetCooperateDetail',
        ),
        migrations.AddField(
            model_name='petcooperatedescimg',
            name='cooperate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userBack.petcooperateinfo', verbose_name='所属机构'),
        ),
    ]
