# Generated by Django 4.0.3 on 2022-04-26 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0018_heartlogo_alter_heartinfo_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HearDetailImage',
            new_name='HeartDetailImage',
        ),
        migrations.AlterModelOptions(
            name='heartdetailimage',
            options={'verbose_name': '缅怀详情图片', 'verbose_name_plural': '缅怀详情图片'},
        ),
        migrations.AlterModelTable(
            name='heartdetailimage',
            table='heart_detail_image',
        ),
    ]
