# Generated by Django 4.0.3 on 2022-04-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0021_alter_heartinfo_pet_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartdetailimage',
            name='heart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userBack.heartinfo', verbose_name='所属的缅怀详情'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartdetailimage',
            name='img',
            field=models.ImageField(default='狗_2.jpg', upload_to='', verbose_name='描述图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heartlogo',
            name='title',
            field=models.CharField(choices=[('宠物狗', '宠物狗'), ('宠物猫', '宠物猫'), ('功勋犬', '功勋犬'), ('个人的', '个人的')], default='宠物狗', max_length=30, verbose_name='标题'),
        ),
    ]
