# Generated by Django 4.0.3 on 2022-04-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userBack', '0022_remove_heartinfo_detail_heartdetailimage_heart_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='heartinfo',
        #     name='detail',
        # ),
        # migrations.DeleteModel(
        #     name='HeartDetail',
        # ),
    ]
